[project]
name = "tasks-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kamil Khursandov", email = "khursandov.kamil@gmail.com" }
]
requires-python = ">=3.15.0"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi>=0.143.0",
    "pydantic>=2.14.0",
    "sqlalchemy[asyncio]>=2.1.4",
    "uvicorn>=0.54.0",
]

[project.scripts]
tasks-fastapi = "tasks_fastapi:main"

[build-system]
requires = ["uv_build>=0.13.0,<0.14.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.17.0",
]
